export const MateriasLicenciaturaInformatica = [
  {
    bloque: '1er',
    id: 1,
    materias: [
      {
        id: 1,
        asignatura: 'Matemática I',
        area: 'CB',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 2,
        asignatura: 'Introducción a la programación',
        area: 'AyL',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 3,
        asignatura: 'Organización de computadoras',
        area: 'ASOyR',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 4,
        asignatura: 'Nuevos entornos y lenguajes',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 5,
        asignatura: 'Estructuras de datos',
        area: 'TC',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: ['Introducción a la programación'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 6,
        asignatura: 'Programación con objetos I',
        area: 'AyL',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: ['Introducción a la programación'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 7,
        asignatura: 'Bases de datos',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Matemática I'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 8,
        asignatura: 'Inglés I',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: null,
      },
    ],
  },
  {
    bloque: '2do',
    id: 2,
    materias: [
      {
        id: 9,
        asignatura: 'Matemática II',
        area: 'CB',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Matemática I'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 10,
        asignatura: 'Programación con objetos II',
        area: 'AyL',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación con Objetos I'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 11,
        asignatura: 'Redes de computadoras',
        area: 'ASOyR',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Organización de Computadoras'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 12,
        asignatura: 'Sistemas operativos',
        area: 'ASOyR',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [
          'Organización de computadoras',
          'Introducción a la programación',
        ],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 13,
        asignatura: 'Programación funcional',
        area: 'AyL',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Estructuras de datos'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 14,
        asignatura: 'Construcción de interfaces de usuario',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación con objetos II'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 15,
        asignatura: 'Algoritmos',
        area: 'AyL',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación funcional'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 16,
        asignatura: 'Estrategias de persistencia',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación con objetos II', 'Bases de datos'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 17,
        asignatura: 'Laboratorio de sistemas operativos y redes',
        area: 'ASOyR',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Redes de computadoras', 'Sistemas operativos'],
        estado: 'Pendiente',
        calificacion: null,
      },
    ],
  },
  {
    bloque: '3er',
    id: 3,
    materias: [
      {
        id: 18,
        asignatura: 'Análisis matemático',
        area: 'CB',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Matemática II'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 19,
        asignatura: 'Lógica y programación',
        area: 'TC',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Matemática I', 'Introducción a la programación'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 20,
        asignatura: 'Elementos de ingeniería de software',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación con objetos II'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 21,
        asignatura: 'Seguridad de la información',
        area: 'ASOyR',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Laboratorio de sistemas operativos y redes'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 22,
        asignatura: 'Materia UNAHUR',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 23,
        asignatura: 'Inglés II',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: ['Inglés I'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 24,
        asignatura: 'Matemática III',
        area: 'CB',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Matemática II'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 25,
        asignatura: 'Programación concurrente',
        area: 'AyL',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Estructuras de datos'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 26,
        asignatura: 'Ingeniería de requerimientos',
        area: 'ISBDySI',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Elementos de ingeniería de software'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 27,
        asignatura: 'Desarrollo de aplicaciones',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [
          'Construcción de interfaces de usuario',
          'Estrategias de persistencia',
          'Elementos de ingeniería de software',
        ],
        estado: 'Pendiente',
        calificacion: null,
      },
    ],
  },
  {
    bloque: '4to',
    id: 4,
    materias: [
      {
        id: 28,
        asignatura: 'Probabilidad y estadística',
        area: 'CB',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Matemática III'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 29,
        asignatura: 'Gestión de proyectos de desarrollo de software',
        area: 'ISBDySI',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Ingeniería de requerimientos'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 30,
        asignatura: 'Lenguajes formales y autómatas',
        area: 'TC',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Lógica y programación'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 31,
        asignatura: 'Programación con objetos III',
        area: 'AyL',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Programación con objetos II'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 32,
        asignatura: 'Materia UNAHUR II',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 33,
        asignatura: 'Práctica profesional supervisada',
        area: null,
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [
          'Programación funcional',
          'Laboratorio de sistemas operativos y redes',
          'Programación concurrente',
          'Desarrollo de aplicaciones',
        ],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 34,
        asignatura: 'Teoría de la computación',
        area: 'TC',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Lenguajes formales y autómatas'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 35,
        asignatura: 'Arquitectura de software I',
        area: 'ISBDySI',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [
          'Elementos de ingiería de software',
          'Programación concurrente',
          'Desarrollo de aplicaciones',
          'Gestión de proyectos de desarrollo de software',
        ],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 36,
        asignatura: 'Sistemas distribuidos y tiempo real',
        area: 'ASOyR',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [
          'Laboratorios de sistemas operativos y redes',
          'Programación concurrente',
        ],
        estado: 'Pendiente',
        calificacion: null,
      },
    ],
  },
  {
    bloque: '5to',
    id: 5,
    materias: [
      {
        id: 37,
        asignatura: 'Tesina de licenciatura',
        area: 'Otros',
        hsSemanales: '5',
        cargaHorariaTotal: '160',
        correlativas: [
          'Gestión de proyectos de desarrollo de software',
          'Lenguajes formales y autómatas',
          'Programación con objetos III',
        ],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 38,
        asignatura: 'Electiva I',
        area: 'Compl',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        opciones: [
          'Bases de datos II',
          'Fundamentos de aprendizaje automático',
          'Introducción a la bioinformática',
          'Políticas públicas en la sociedad de la información y la era digital',
          'Sistemas de la información geográfica',
          'Introducción al desarrollo de videojuegos',
          'Análisis estático de programas y herramientas asociadas',
          'Semántica de lenguajes de programación',
          'Administración de las organizaciones',
        ],
        correlativas: [
          'Bases de datos',
          'Programación con objetos II',
          'Elementos de ingeniería de software',
          'Programación concurrente',
        ],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 39,
        asignatura: 'Características de lenguajes de programación',
        area: 'AyL',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Lógica y programación'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 40,
        asignatura: 'Arquitectura de software II',
        area: 'ISBDySI',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [
          'Arquitectura de software I',
          'Sistemas distribuidos y tiempo real',
        ],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 41,
        asignatura: 'Arquitectura de computadoras',
        area: 'ASOyR',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Laboratorio de sistemas operativos y redes'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 42,
        asignatura: 'Electiva II',
        area: 'Compl',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        opciones: [
          'Bases de datos II',
          'Fundamentos de aprendizaje automático',
          'Introducción a la bioinformática',
          'Políticas públicas en la sociedad de la información y la era digital',
          'Sistemas de la información geográfica',
          'Introducción al desarrollo de videojuegos',
          'Análisis estático de programas y herramientas asociadas',
          'Semántica de lenguajes de programación',
          'Administración de las organizaciones',
        ],
        correlativas: [
          'Bases de datos',
          'Programación con objetos II',
          'Elementos de ingeniería de software',
          'Programación concurrente',
        ],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 43,
        asignatura: 'Parseo y generación de código',
        area: 'AyL',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [
          'Lenguajes formales y autómatas',
          'Características de lenguajes de programación',
        ],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 44,
        asignatura: 'Ejercicio profesional',
        area: 'APyS',
        hsSemanales: '3',
        cargaHorariaTotal: '48',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 45,
        asignatura: 'Tecnología y sociedad',
        area: 'APyS',
        hsSemanales: '3',
        cargaHorariaTotal: '48',
        correlativas: ['Ejercicio profesional'],
        estado: 'Pendiente',
        calificacion: null,
      },
    ],
  },
];
