export const MateriasLicenciaturaInformatica = [
  {
    bloque: 'Primer Año',
    id: 1,
    materias: [
      {
        id: 1,
        asignatura: 'Matemática I',
        area: 'CB',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 2,
        asignatura: 'Introducción a la programación',
        area: 'AyL',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 3,
        asignatura: 'Organización de computadoras',
        area: 'ASOyR',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 4,
        asignatura: 'Nuevos entornos y lenguajes',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 5,
        asignatura: 'Estructuras de datos',
        area: 'TC',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: ['Introducción a la programación'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 6,
        asignatura: 'Programación con objetos I',
        area: 'AyL',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: ['Introducción a la programación'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 7,
        asignatura: 'Bases de datos',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Matemática I'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 8,
        asignatura: 'Inglés I',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
  {
    bloque: 'Segundo Año',
    id: 2,
    materias: [
      {
        id: 9,
        asignatura: 'Matemática II',
        area: 'CB',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Matemática I'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 10,
        asignatura: 'Programación con objetos II',
        area: 'AyL',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación con Objetos I'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 11,
        asignatura: 'Redes de computadoras',
        area: 'ASOyR',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Organización de Computadoras'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 12,
        asignatura: 'Sistemas operativos',
        area: 'ASOyR',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [
          'Organización de Computadoras',
          'Introducción a la Programación',
        ],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 13,
        asignatura: 'Programación funcional',
        area: 'AyL',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Estructuras de datos'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 14,
        asignatura: 'Construcción de interfaces de usuario',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación con objetos II'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 15,
        asignatura: 'Algoritmos',
        area: 'AyL',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 16,
        asignatura: 'Estrategias de persistencia',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación con objetos II', 'Bases de datos'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 17,
        asignatura: 'Laboratorio de sistemas operativos y redes',
        area: 'ASOyR',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Redes de computadoras', 'Sistemas operativos'],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
  {
    bloque: 'Tercer Año',
    id: 3,
    materias: [
      {
        id: 18,
        asignatura: 'Análisis matemático',
        area: 'CB',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 19,
        asignatura: 'Lógica y programación',
        area: 'TC',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 20,
        asignatura: 'Elementos de ingeniería de software',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación con objetos II'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 21,
        asignatura: 'Seguridad de la información',
        area: 'ASOyR',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Inglés I'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 22,
        asignatura: 'Materia UNAHUR',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 23,
        asignatura: 'Inglés II',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: ['Inglés I'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 24,
        asignatura: 'Matemática III',
        area: 'CB',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Matemática II'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 25,
        asignatura: 'Programación concurrente',
        area: 'AyL',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Estructuras de datos'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 26,
        asignatura: 'Ingeniería de requerimientos',
        area: 'ISBDySI',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 27,
        asignatura: 'Desarrollo de aplicaciones',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [
          'Construcción de interfaces de usuario',
          'Estrategias de persistencia',
          'Elementos de ingeniería de software',
          'Matemática II',
        ],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
  {
    bloque: 'Cuarto Año',
    id: 4,
    materias: [
      {
        id: 28,
        asignatura: 'Probabilidad y Estadística',
        area: 'CB',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 29,
        asignatura: 'Gestión de Proyectos de Desarrollo de Software',
        area: 'ISBDySI',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 30,
        asignatura: 'Lenguajes Formales y Autómatas',
        area: 'TC',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 31,
        asignatura: 'Programación con Objetos III',
        area: 'AyL',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 32,
        asignatura: 'Materia UNAHUR II',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 33,
        asignatura: 'Práctica Profesional Supervisada',
        area: '',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [
          'Desarrollo de Aplicaciones',
          'Programación Funcional',
          'Programación Concurrente',
          'Laboratorio de Sistemas',
          'Operativos y Redes',
        ],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 34,
        asignatura: 'Teoría de la Computación',
        area: 'TC',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 35,
        asignatura: 'Arquitectura de Software I',
        area: 'ISBDySI',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 36,
        asignatura: 'Sistemas Distribuidos y Tiempo Real',
        area: 'ASOyR',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
  {
    bloque: 'Quinto Año',
    id: 5,
    materias: [
      {
        id: 37,
        asignatura: 'Tesina de Licenciatura',
        area: 'Otros',
        hsSemanales: '5',
        cargaHorariaTotal: '160',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 38,
        asignatura: 'Complementaria',
        area: 'Compl',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [
          'Bases de Datos',
          'Programación con Objetos II',
          'Elementos de Ingeniería de Software',
          'Programación Concurrente',
        ],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 39,
        asignatura: 'Características de Lenguajes de Programación',
        area: 'AyL',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 40,
        asignatura: 'Arquitectura de Software II',
        area: 'ISBDySI',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 41,
        asignatura: 'Arquitectura de Computadoras',
        area: 'ASOyR',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 42,
        asignatura: 'Complementaria II',
        area: 'Compl',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [
          'Bases de Datos',
          'Programación con Objetos II',
          'Elementos de Ingeniería de Software',
          'Programación Concurrente',
        ],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 43,
        asignatura: 'Parseo y generación de código',
        area: 'AyL',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 44,
        asignatura: 'Ejercicio Profesional',
        area: 'APyS',
        hsSemanales: '3',
        cargaHorariaTotal: '48',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        id: 45,
        asignatura: 'Tecnología y Sociedad',
        area: 'APyS',
        hsSemanales: '3',
        cargaHorariaTotal: '48',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
];
