export const MateriasLicenciaturaInformatica = [
  {
    bloque: 'Primer Año',
    materias: [
      {
        asignatura: 'Matemática I',
        area: 'CB',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Introducción a la Programación',
        area: 'AyL',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Organización de computadoras',
        area: 'ASOyR',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Nuevos entornos y lenguajes',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Estructuras de Datos',
        area: 'TC',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: ['Introducción a la Programación'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Programación con Objetos I',
        area: 'AyL',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: ['Introducción a la Programación'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Bases de Datos',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Matemática I'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Inglés I',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
  {
    bloque: 'Segundo Año',
    materias: [
      {
        asignatura: 'Matemática II',
        area: 'CB',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Matemática I'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Programación con Objetos II',
        area: 'AyL',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación con Objetos I'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Redes de Computadoras',
        area: 'ASOyR',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Organización de Computadoras'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Sistemas Operativos',
        area: 'ASOyR',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [
          'Organización de Computadoras',
          'Introducción a la Programación',
        ],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Programación Funcional',
        area: 'AyL',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Estructuras de Datos'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Construcción de Interfaces de Usuario',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación de objetos II'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Algoritmos',
        area: 'AyL',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Estrategias de Persistencia',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación con Objetos II', 'Bases de Datos'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Laboratorio de Sistemas Operativos y Redes',
        area: 'ASOyR',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Redes de Computadoras', 'Sistemas Operativos'],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
  {
    bloque: 'Tercer Año',
    materias: [
      {
        asignatura: 'Análisis Matemático',
        area: 'CB',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Lógica y Programación',
        area: 'TC',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Elementos de Ingeniería de Software',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación con Objetos II'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Seguridad de la Información',
        area: 'ASOyR',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Inglés I'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Materia UNAHUR',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Inglés II',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: ['Inglés I'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Matemática III',
        area: 'CB',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Matemática II'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Programación Concurrente',
        area: 'AyL',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Estructuras de Datos'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Ingeniería de Requerimientos',
        area: 'ISBDySI',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Desarrollo de Aplicaciones',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [
          'Construcción de Interfaces de Usuario',
          'Estrategias de Persistencia',
          'Elementos de Ingeniería de Software',
          'Matemática II',
        ],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
  {
    bloque: 'Cuarto Año',
    materias: [
      {
        asignatura: 'Probabilidad y Estadística',
        area: 'CB',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Gestión de Proyectos de Desarrollo de Software',
        area: 'ISBDySI',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Lenguajes Formales y Autómatas',
        area: 'TC',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Programación con Objetos III',
        area: 'AyL',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Materia UNAHUR II',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Práctica Profesional Supervisada',
        area: '',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [
          'Desarrollo de Aplicaciones',
          'Programación Funcional',
          'Programación Concurrente',
          'Laboratorio de Sistemas',
          'Operativos y Redes',
        ],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Teoría de la Computación',
        area: 'TC',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Arquitectura de Software I',
        area: 'ISBDySI',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Sistemas Distribuidos y Tiempo Real',
        area: 'ASOyR',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
  {
    bloque: 'Quinto Año',
    materias: [
      {
        asignatura: 'Tesina de Licenciatura',
        area: 'Otros',
        hsSemanales: '5',
        cargaHorariaTotal: '160',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Complementaria',
        area: 'Compl',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [
          'Bases de Datos',
          'Programación con Objetos II',
          'Elementos de Ingeniería de Software',
          'Programación Concurrente',
        ],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Características de Lenguajes de Programación',
        area: 'AyL',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Arquitectura de Software II',
        area: 'ISBDySI',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Arquitectura de Computadoras',
        area: 'ASOyR',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Complementaria II',
        area: 'Compl',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [
          'Bases de Datos',
          'Programación con Objetos II',
          'Elementos de Ingeniería de Software',
          'Programación Concurrente',
        ],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Parseo y generación de código',
        area: 'AyL',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Ejercicio Profesional',
        area: 'APyS',
        hsSemanales: '3',
        cargaHorariaTotal: '48',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Tecnología y Sociedad',
        area: 'APyS',
        hsSemanales: '3',
        cargaHorariaTotal: '48',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
];
