export const MateriasTecnicaturaProgramacion = [
  {
    bloque: 'Primer Cuatrimestre',
    materias: [
      {
        asignatura: 'Matemática para Informática I',
        area: 'CB',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Introducción a lógica y problemas computacionales',
        area: 'AyL',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Organización de computadoras I',
        area: 'ASOyR',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Nuevos entornos y lenguajes',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
  {
    bloque: 'Segundo Cuatrimestre',
    materias: [
      {
        asignatura: 'Taller de lenguajes de marcado y tecnologías web',
        area: 'TC',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Introducción a lógica y problemas computacionales'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Programación estructurada',
        area: 'AyL',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Introducción a lógica y problemas computacionales'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Matemática para Informática II',
        area: 'CB',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Matemática para informática I'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Inglés I',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
  {
    bloque: 'Tercer Cuatrimestre',
    materias: [
      {
        asignatura: 'Bases de Datos',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Matemática para informática II'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Programación de objetos I',
        area: 'AyL',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: ['Programación estructurada'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Estructuras de datos',
        area: 'TC',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: ['Programación estructurada'],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
  {
    bloque: 'Cuarto Cuatrimestre',
    materias: [
      {
        asignatura: 'Materia UNAHUR',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Programación de objetos II',
        area: 'AyL',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación de objetos I'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Electiva I',
        area: 'Elec',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Programación estructurada', 'Estructuras de datos'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Electiva II',
        area: 'Elec',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Organización de computadoras I'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Inglés II',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: ['Inglés I'],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
  {
    bloque: 'Quinto Cuatrimestre',
    materias: [
      {
        asignatura: 'Construcción de interfaces de usuario',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación de objetos II'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Estrategias de persistencia',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación de objetos II', 'Bases de datos'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Elementos de ingeniería de software',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación de objetos II'],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
];
