export const MateriasTecnicaturaProgramacion = [
  {
    bloque: '1er',
    id: 1,
    materias: [
      {
        id: 1,
        asignatura: 'Matemática para informática I',
        area: 'CB',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 2,
        asignatura: 'Introducción a lógica y problemas computacionales',
        area: 'AyL',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 3,
        asignatura: 'Organización de computadoras I',
        area: 'ASOyR',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 4,
        asignatura: 'Nuevos entornos y lenguajes',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: null,
      },
    ],
  },
  {
    bloque: '2do',
    id: 2,
    materias: [
      {
        id: 5,
        asignatura: 'Taller de lenguajes de marcado y tecnologías web',
        area: 'TC',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Introducción a lógica y problemas computacionales'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 6,
        asignatura: 'Programación estructurada',
        area: 'AyL',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Introducción a lógica y problemas computacionales'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 7,
        asignatura: 'Matemática para informática II',
        area: 'CB',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Matemática para informática I'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 8,
        asignatura: 'Inglés I',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: null,
      },
    ],
  },
  {
    bloque: '3er',
    id: 3,
    materias: [
      {
        id: 9,
        asignatura: 'Bases de datos',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Matemática para informática II'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 10,
        asignatura: 'Programación con objetos I',
        area: 'AyL',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: ['Programación estructurada'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 11,
        asignatura: 'Estructuras de datos',
        area: 'TC',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: ['Programación estructurada'],
        estado: 'Pendiente',
        calificacion: null,
      },
    ],
  },
  {
    bloque: '4to',
    id: 4,
    materias: [
      {
        id: 12,
        asignatura: 'Materia UNAHUR',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 13,
        asignatura: 'Programación con objetos II',
        area: 'AyL',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación con objetos I'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 14,
        asignatura: 'Electiva I',
        opciones: ['Programación funcional', 'Programación concurrente'],
        area: 'Elec',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Programación estructurada', 'Estructuras de datos'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 15,
        asignatura: 'Electiva II',
        opciones: [
          'Organización de computadoras II',
          'Redes de computadoras',
          'Sistemas operativos',
        ],
        area: 'Elec',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Organización de computadoras I'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 16,
        asignatura: 'Inglés II',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: ['Inglés I'],
        estado: 'Pendiente',
        calificacion: null,
      },
    ],
  },
  {
    bloque: '5to',
    id: 5,
    materias: [
      {
        id: 17,
        asignatura: 'Construcción de interfaces de usuario',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación con objetos II'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 18,
        asignatura: 'Estrategias de persistencia',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación con objetos II', 'Bases de datos'],
        estado: 'Pendiente',
        calificacion: null,
      },
      {
        id: 19,
        asignatura: 'Elementos de ingeniería de software',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación con objetos II'],
        estado: 'Pendiente',
        calificacion: null,
      },
    ],
  },
];
