export const MateriasTecnicaturaInformatica = [
  {
    bloque: 'Primer Cuatrimestre',
    materias: [
      {
        asignatura: 'Matemática I',
        area: 'CB',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Introducción a la programación',
        area: 'AyL',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Organización de computadoras',
        area: 'ASOyR',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Nuevos entornos y lenguajes',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
  {
    bloque: 'Segundo Cuatrimestre',
    materias: [
      {
        asignatura: 'Estructuras de datos',
        area: 'TC',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: ['Introducción a la programación'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Programación con Objetos I',
        area: 'AyL',
        hsSemanales: '8',
        cargaHorariaTotal: '128',
        correlativas: ['Introducción a la programación'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Bases de datos',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Matemática I'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Inglés I',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
  {
    bloque: 'Tercer Cuatrimestre',
    materias: [
      {
        asignatura: 'Matemática II',
        area: 'CB',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Matemática I'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Programación con Objetos II',
        area: 'AyL',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación con Objetos I'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Redes de computadoras',
        area: 'ASOyR',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Organización de computadoras'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Sistemas operativos',
        area: 'ASOyR',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [
          'Organización de computadoras',
          'Introducción a la programación',
        ],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
  {
    bloque: 'Cuarto Cuatrimestre',
    materias: [
      {
        asignatura: 'Construcción de interfaces de usuario',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación con objetos II'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Programación concurrente',
        area: 'AyL',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Estructuras de datos'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Estrategias de persistencia',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación con objetos II', 'Bases de datos'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Elementos de ingeniería de software',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: ['Programación con objetos II'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Inglés II',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: ['Inglés I'],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
  {
    bloque: 'Quinto Cuatrimestre',
    materias: [
      {
        asignatura: 'Programación funcional',
        area: 'AyL',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Estructuras de datos'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Laboratorio de sistemas operativos y redes',
        area: 'ASOyR',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: ['Redes de computadoras', 'Sistemas operativos'],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Desarrollo de aplicaciones',
        area: 'ISBDySI',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [
          'Construcción de interfaces de usuario',
          'Estrategias de persistencia',
          'Elementos de ingeniería de software',
          'Matemática II',
        ],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Complementaria',
        area: 'Compl',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [
          'Programación con objetos II',
          'Elementos de ingeniería de software',
          'Programación concurrente',
        ],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
  {
    bloque: 'Sexto Cuatrimestre',
    materias: [
      {
        asignatura: 'Práctica profesional supervisada',
        area: '',
        hsSemanales: '6',
        cargaHorariaTotal: '96',
        correlativas: [
          'Desarrollo de aplicaciones',
          'Programación funcional',
          'Programación concurrente',
          'Laboratorio de sistemas',
          'Operativos y redes',
        ],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Materia UNAHUR',
        area: 'Gral',
        hsSemanales: '2',
        cargaHorariaTotal: '32',
        correlativas: [],
        estado: 'Pendiente',
        calificacion: '',
      },
      {
        asignatura: 'Complementaria',
        area: 'Compl',
        hsSemanales: '4',
        cargaHorariaTotal: '64',
        correlativas: [
          'Programación con objetos II',
          'Elementos de ingeniería de software',
          'Programación concurrente',
        ],
        estado: 'Pendiente',
        calificacion: '',
      },
    ],
  },
];
